### ISSUE TITLE
Cannot run Offboard example: Failsafe enabled: No manual control stick input  ROS2

### ISSUE THREAD

**Issue by miferco97** [PX4/px4_ros_com#111]
Hi, I am not able to launch the ros2 offboard example properly.

The steps i made are the same as the tutorial for ROS2 Offboard example:
In one terminal
`$ cd PX4-Autopilot`
`$ make px4_sitl_rtps gazebo`

On other terminal
`$ source px4_ros_com_ros2/install/setup.bash`
`$ micrortps_agent -t UDP`

And finally in other terminal
`$ source px4_ros_com_ros2/install/setup.bash`
`$ ros2 run px4_ros_com offboard_control`

When I launch all, the uav only arms and does not take off.

In px4 terminal this can be shown:

> INFO  [commander] Armed by external command	
> WARN  [commander] Failsafe enabled: No manual control stick input	
> INFO  [commander] Failsafe mode activated	
> INFO  [tone_alarm] battery warning (fast)

Searching in other issues i check the following firmware parameters and I have assigned this values to each one:
- COM_RC_IN_MODE  = 1 
- COM_RCL_EXCEPT = 3
- NAV_RCL_ACT = 0

The same situation happened after doing this.

The only way I had been able to make this code work is by configuring connecting a controller to the computer and enabling a Virtual Joystick on QGroundControl (AND CHANGING COM_RCL_IN_MODE -> 2).
Is there any way to simulate without attaching a controller when  COM_RCL_IN_MODE= 1 and  NAV_RCL_ACT = 0 as the documentation  recommends ??

Thanks in advance

**Comment by xiaobai-cai-hold** [comment]
I also meet this problem, it works well according to official instruction when I first build up the whole environment,however i make other  firmware ,it fails like you. any friend can solve it ,thanks

**Comment by Li-Jinjie** [comment]
I am facing the same problem, hoping for solutions please

**Comment by abhishekgoudar** [comment]
Not sure if anyone is still facing a problem. But setting parameter to COM_RCL_EXCEPT=4 worked for me on the latest master branch. 

This is assuming you have valid source of positioning (either GPS or external odometry) is being fed and valid setpoints at appropriate rate are being sent as well.

**Comment by Li-Jinjie** [comment]
@abhishekgoudar It works! Thanks a lot!

**Comment by HuaYuXiao** [comment]
> Not sure if anyone is still facing a problem. But setting parameter to COM_RCL_EXCEPT=4 worked for me on the latest master branch.
> 
> This is assuming you have valid source of positioning (either GPS or external odometry) is being fed and valid setpoints at appropriate rate are being sent as well.

Excuse me, I have already set parameters in QGC, but what does "valid setpoints at appropriate rate are being sen" mean? ThankU so much!
