### ISSUE TITLE
Unexpected topic ID '62' to publish

### ISSUE THREAD

**Issue by Vit-A-Cuss** [PX4/px4_ros_com#136]
Ubuntu 20.04
ROS2 Foxy
Gazebo 
PX4-Autopilot (Stable Release v1.12.3)

I was following this tutorial ( https://docs.px4.io/v1.12/en/ros/ros2_comm.html ) and : 
- I have installed the latest Fast RTPS(DDS) and the Fast-RTPS-Gen 1.0.4 with the required dependencies
- I have installed ROS 2 Foxy
- I built the workspace with the latest px4_ros_com and px4_msgs

When I start the Sanity Check I get this error in the second terminal (micrortps_agent) 
_[   micrortps_agent   ]	Unexpected topic ID '62' to publish. Please make sure the agent is capable of parsing the message associated to the topic ID '62'_
and the listener does not provide any data. 
I have not modified any stock file.

How can I fix this problem? Thanks in advance

**Comment by TSC21** [comment]
It means you do not have px4_ros_com and PX4 in sync. As specified on the docs, the user either had to use the latest code on both sides, or it has to find the correpondent commit in px4_ros_com that matches the release he is trying to use (in this case 1.12). I recommend that you use the latest in both.
