### ISSUE TITLE
vehicle_gps_position_listener.cpp doesnt give any information

### ISSUE THREAD

**Issue by AEGEAN99** [PX4/px4_ros_com#142]
Hello, I have an issue with vehicle_gps_position_listener.cpp. When I run it with sitl gazebo it doesnt give any information. Everything works perfectly except vehicle_gps_position_listener.cpp for me. I need to get gps position in my project.
Thank you for the effort:DDD

**Comment by Cristian-wp** [comment]
Hello, I have the same problem with ROS2 Humble and PX4 v14.
I can see the GPS position from `/fmu/out/vehicle_global_position` but I can not see the raw datas.
What can be the problem?
