### ISSUE TITLE
Update the generate_microRTPS_bridge to cover ROS humble distribution

### ISSUE THREAD

**Issue by nigeltiany** [PX4/px4_ros_com#151]
The script generate_microRTPS_bridge is out of date with https://github.com/PX4/PX4-Autopilot/blob/0061ef8b89f4ee1799803597149046e420ac631a/msg/tools/generate_microRTPS_bridge.py 

The main issue this is causing is; ROS Humble distributions do not have the ros2 type definitions generated in a non-conflicting way. This leads to an issue where the data is not exchanged between ROS and Pixhawk. It also means that the documentation/tutorial cannot be successfully run. 

https://docs.px4.io/main/en/ros/ros2_comm.html#build-ros-2-workspace

> To create and build the workspace:

> Create a workspace directory using:
> $ mkdir -p ~/px4_ros_com_ros2/src
> Clone the ROS 2 bridge packages px4_ros_com and px4_msgs to the /src directory (the master branch is cloned by default):
> $ git clone https://github.com/PX4/px4_ros_com.git ~/px4_ros_com_ros2/src/px4_ros_com
> $ git clone https://github.com/PX4/px4_msgs.git ~/px4_ros_com_ros2/src/px4_msgs
> Use the build_ros2_workspace.bash script to build the ROS 2 workspace (including px4_ros_com and px4_msgs).
> $ cd ~/px4_ros_com_ros2/src/px4_ros_com/scripts
> $ source build_ros2_workspace.bash

**Comment by TSC21** [comment]
@nigeltiany maybe I wasn't clear: this issue needs to be opened in the PX4-Autopilot repo. The CI/CD pipeline that deploys the script is there, not here. Closing to avoid confusion.
