### ISSUE TITLE
Issue with PX4 ros/gazebo install scripts

### ISSUE THREAD

**Issue by mlautman** [PX4/px4_ros_com#21]
Using the [install script](https://raw.githubusercontent.com/PX4/Devguide/master/build_scripts/ubuntu_sim_ros_gazebo.sh) is broken in a few ways. For one it installs ROS kinetic rather than melodic which is assumed [later in the documentation](https://dev.px4.io/en/middleware/micrortps.html#installing-ros-and-ros2-and-respective-dependencies). Also, the script silently makes undesirable changes to the user's `.bashrc`. This can be considered a bug as running `rossource="source /opt/ros/kinetic/setup.bash"` at the start of every terminal session causes issues when you are trying to create a pure ROS2 project.

**Comment by TSC21** [comment]
@mlautman that specific ROS script you talk about is somewhat out-of-scope for this package. This should be brought for the PX4 Devguide itself. Can you please do that?
