### ISSUE TITLE
sensor_combined_listener can not receive the msg from micrortps_agent

### ISSUE THREAD

**Issue by CarmChao** [PX4/px4_ros_com#35]
After I finished all the compilation, and run the example. It doesn't work, the ros2 node sensor_combined_listener receive nothing from the micrortps_agent. However the micrortps_agent received messages from micrortps_client. And I use ros2 topic echo /SensorCombined_PubSubTopic,
it says:
Cannot echo topic '/SensorCombined_PubSubTopic', as it contains more than one type: [px4_msgs::msg::SensorCombined, px4_msgs/msg/SensorCombined]
and I found in the micrortps_agent it's SensorCombined_PubSubTopic's type is px4_msgs::msg::SensorCombined while in sensor_combined_listener the SensorCombined_PubSubTopic's type is px4_msgs/msg/SensorCombined

**Comment by ldg810** [comment]
@CarmChao Which version of ROS are you using? If you using dashing, the problem was solved in last week.
Please check this [Issue](https://github.com/eProsima/Fast-RTPS/issues/829).
