### ISSUE TITLE
Error when I try to build px4_ros_com_ros2 package : error: ‘class eprosima::fastrtps::rtps::BuiltinAttributes’ has no member named ‘leaseDuration’

### ISSUE THREAD

**Issue by bastientaillandier** [PX4/px4_ros_com#42]
Hi !

I'm on ROS2-Eloquent and I follow this doc : https://dev.px4.io/master/en/middleware/micrortps.html
And I follow this page to install Fast-RTPS and Fast-RTPS-Gen : https://dev.px4.io/master/en/setup/fast-rtps-installation.html

The installation of FastRTPS-1.8.2 and FastRTPS-Gen succeed.

Then I cloned the repo of px4_ros_com_ros2 and I don't need the ros1 bridge then I didn't clone it.

And when I tried to build px4_ros_com_ros2 package with build_ros2_workspace.bash, my terminal just close and did nothing and when I build (after clean_all.bash) with this command : colcon build --symlink-install --packages-skip ros1_bridge --event-handlers console_direct+
I get this issue :

![Screenshot from 2020-04-10 08-53-24](https://user-images.githubusercontent.com/36010474/79004092-e038e000-7b08-11ea-9a1a-797ea5ba40ea.png)
![Screenshot from 2020-04-10 08-53-46](https://user-images.githubusercontent.com/36010474/79004096-e333d080-7b08-11ea-9bbe-dbf4e761ef3c.png)
![Screenshot from 2020-04-10 08-53-56](https://user-images.githubusercontent.com/36010474/79004100-e4fd9400-7b08-11ea-8d13-bb282bfdc0c4.png)

Thank's a lot for helping me !

**Comment by TSC21** [comment]
@bastientaillandier use `./build_ros2_workspace.bash` instead of `source ...`.

What version of the Firmware are you using? Please clone and use PX4 master.

Also make sure that `fastrtpsgen -version` returns `1.0.4`.

**Comment by bastientaillandier** [comment]
I clone the the PX4 master and fastrtpsgen -version return 1.0.4.
When I tried to use ./build_ros2_workspace.bash I get this issue : 
![Screenshot from 2020-04-12 23-14-38](https://user-images.githubusercontent.com/36010474/79096979-70e30c00-7d13-11ea-9804-5b5c6c048496.png)

any idea ?

**Comment by bastientaillandier** [comment]
An other version of FastRtps was installed during the installation of ROS2-Eloquent.
I just rm -rf /opt/ros/eloquent/share/fastrtps and fastcdr and it solved my problem.
Thank you

**Comment by TSC21** [comment]
> An other version of FastRtps was installed during the installation of ROS2-Eloquent.
> I just rm -rf /opt/ros/eloquent/share/fastrtps and fastcdr and it solved my problem.
> Thank you

You are not supposed to delete those versions.

**Comment by bastientaillandier** [comment]
If I don't delete Eloquent's version in `/opt/ros/eloquent/`, the wrong version of FastRTPS (1.9.3) is used to build the workspace and the compilation error in my first screenshot occurs.

What is your own compilation process for building the workspace ?

Here is what I did :
- [install Fast-RTPS 1.8.2 from source](https://dev.px4.io/master/en/setup/fast-rtps-installation.html)
- install Fast-RTPS-GEN (`fastrtpsgen -version` return 1.0.4)
- create a ws with px4_ros_com, px4_msgs and Firmware, all on `master`
- `make px4_sitl_rtps`
- `sudo ./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge --ros_distro eloquent --ros_path /opt/ros/eloquent/setup.bash`

Then when I tried `micrortps_agent -t UDP` I had the following error:
`micrortps_agent: symbol lookup error: micrortps_agent: undefined symbol: _ZN8eprosima8fastrtps11Parameter_tC2Ev`

**Comment by TSC21** [comment]
> `sudo ./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge --ros_distro eloquent --ros_path /opt/ros/eloquent/setup.bash`

This is wrong. You are not supposed to run that script with sudo.

**Comment by bastientaillandier** [comment]
> > `sudo ./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge --ros_distro eloquent --ros_path /opt/ros/eloquent/setup.bash`
> 
> This is wrong. You are not supposed to run that script with sudo.

I tried without sudo too and it did the same error. I just use sudo because somewhere it said : Permission denied

**Comment by TSC21** [comment]
Also, if you are using ROS2 Eloquent, then you do have to install Fast-RTPS 1.9.3, not 1.8.2. That's why we always match the supported versions of Fast-RTPS with the ones being used on the ROS2 package dependencies.
Meaning:
- ROS2 Eloquent - install Fast-RTPS 1.9.3
- ROS2 Dashing - install Fast-RTPS 1.8.2.

You don't find any information on the docs regarding this because we officially offer support to ROS2 Dashing, since it's LTS.

`./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge` should be enough.

**Comment by TSC21** [comment]
> > > `sudo ./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge --ros_distro eloquent --ros_path /opt/ros/eloquent/setup.bash`
> > 
> > 
> > This is wrong. You are not supposed to run that script with sudo.
> 
> I tried without sudo too and it did the same error. I just use sudo because somewhere it said : Permission denied

That's because you already used it with sudo before and now you have all your build, log and install files requiring sudo permissions.

**Comment by bastientaillandier** [comment]
> > > > `sudo ./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge --ros_distro eloquent --ros_path /opt/ros/eloquent/setup.bash`
> > > 
> > > 
> > > This is wrong. You are not supposed to run that script with sudo.
> > 
> > 
> > I tried without sudo too and it did the same error. I just use sudo because somewhere it said : Permission denied
> 
> That's because you already used it with sudo before and now you have all your build, log and install files requiring sudo permissions.

Ok thank you !

**Comment by bastientaillandier** [comment]
> Also, if you are using ROS2 Eloquent, then you do have to install Fast-RTPS 1.9.3, not 1.8.2. That's why we always match the supported versions of Fast-RTPS with the ones being used on the ROS2 package dependencies.
> Meaning:
> 
> * ROS2 Eloquent - install Fast-RTPS 1.9.3
> * ROS2 Dashing - install Fast-RTPS 1.8.2.
> 
> You don't find any information on the docs regarding this because we officially offer support to ROS2 Dashing, since it's LTS.
> 
> `./src/px4_ros_com/scripts/build_ros2_workspace.bash --no_ros1_bridge` should be enough.

Ok I use the Fast-RTPS-1.9.3 with Eloquent and it works well.
But I use fastrtpsgen 1.0.2 (by default with the binaries of the 1.9.3 version). I think it work anyway but I'm not sure because micrortps_client display : command not found. The agent work.
Does  PX4/Firmware starts the Client as a permanent daemon process now ?

**Comment by TSC21** [comment]
> But I use fastrtpsgen 1.0.2 (by default with the binaries of the 1.9.3 version). I think it work anyway but I'm not sure because micrortps_client display : command not found. The agent work.

You need 1.0.4 because of the way that the Publisher/Subscribers are generated. I am sure that it builds but it won't work if you try to get any data on a ROS2 node.

> Does PX4/Firmware starts the Client as a permanent daemon process now ?
No. The command is `micrortps_client start` and you need to build a PX4 target with `_rtps` suffix (ex. `make px4_sitl_rtps`).
