### ISSUE TITLE
build_all.sh script exits without any erros

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [PX4/px4_ros_com#43]
Most likely this is related to my system, but when I run makes the script exit without any errors. (or even if there was a error, the scripts exits and closes the terminal)

```
source build_all.bash --ros1_ws_dir <path/to/px4_ros_com_ros1/ws>
```

Running the script without source e.g. works without any problems.

```
./build_all.bash --ros1_ws_dir <path/to/px4_ros_com_ros1/ws>
```

Running on Ubuntu 18.04, with ROS2 dashing / ROS melodic

**Comment by TSC21** [comment]
Yeah `source build_all.bash --ros1_ws_dir <path/to/px4_ros_com_ros1/ws>` should not be the way to go. `source` is to be removed from the docs.
