### ISSUE TITLE
libfastrtps installed from ros2 installation is visible at /opt/ros/<eloquent>/lib

### ISSUE THREAD

**Issue by mhallak** [PX4/px4_ros_com#49]
I suggest to move the fast rtps version checking after determinating ros version and ros distro and to add:
`fastrtps_version = subprocess.check_output(
    "ls /opt/ros/ros2_distro/lib | grep libfastrtps", shell=True).decode("utf-8").strip().split('so.')[-1]`
in case 
`fastrtps_version = subprocess.check_output(
    " ldconfig -v | grep libfastrtps", #shell=True).decode("utf-8").strip().split('so.')[-1]` returns error.

**Comment by TSC21** [comment]
@mhallak thanks for the suggestion. Fix in Fix in PX4/Firmware@a7112c4.
