### ISSUE TITLE
Add InputRc to published messages

### ISSUE THREAD

**Issue by dk7xe** [PX4/px4_ros_com#65]
For some usecases like starting video recording on a companion computer or triggering a ROS based (offboard control) mission control execution the status of RC channel is needed in ROS(2). This allows the user to start/stop such functionalities from the RC transmitter.

Therefore `/px4_ros_com/templates/uorb_rtps_message_ids.yaml` entry for `InputRc` to be changed accordingly.
Set `send: true`

Related change on PX4-Autopilot https://github.com/PX4/PX4-Autopilot/issues/16741

**Comment by TSC21** [comment]
Please fell free to make a PR against the PX4-Autopilot repo to update https://github.com/PX4/PX4-Autopilot/blob/master/msg/tools/uorb_rtps_message_ids.yaml.

**Comment by dk7xe** [comment]
@TSC21 https://github.com/PX4/PX4-Autopilot/pull/16743
should i do PR here as well?

**Comment by TSC21** [comment]
> @TSC21 [PX4/PX4-Autopilot#16743](https://github.com/PX4/PX4-Autopilot/pull/16743)
> should i do PR here as well?

Thanks. No. The files here are deployed automatically by the PX4-Autopilot CI whenever a change occurs to them there.

**Comment by TSC21** [comment]
I think we can close this now.
