### ISSUE TITLE
Can't generate microRTPS bridge on non Debian based machine

### ISSUE THREAD

**Issue by benjinne** [PX4/px4_ros_com#77]
https://github.com/PX4/px4_ros_com/blob/master/scripts/generate_microRTPS_bridge.py#L281

The above line in generate_microRTPS_bridge uses dpkg to determine the fastrtps_version and when running on a machine that doesn't have dpkg, the following error is produced:

```Traceback (most recent call last):  File "/data/px4_ros_com_ros4/src/px4_ros_com/scripts/generate_microRTPS_bridge.py", line 281, in <module>
    fastrtps_version = re.search(r'Version:\s*([\dd.]+)', subprocess.check_output(
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'dpkg -s ros-foxy-fastrtps 2>/dev/null | grep -i version' returned non-zero exit status 
```

Is it possible to replace dpkg with a more generic way to get the version?

**Comment by TSC21** [comment]
> https://github.com/PX4/px4_ros_com/blob/master/scripts/generate_microRTPS_bridge.py#L281
> 
> The above line in generate_microRTPS_bridge uses dpkg to determine the fastrtps_version and when running on a machine that doesn't have dpkg, the following error is produced:
> 
> ```
>     fastrtps_version = re.search(r'Version:\s*([\dd.]+)', subprocess.check_output(
>   File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command 'dpkg -s ros-foxy-fastrtps 2>/dev/null | grep -i version' returned non-zero exit status 
> 
> Is it possible to replace dpkg with a more generic way to get the version
> ```

Maybe. Do you have another suggestion? If yes, feel free to issue a PR against PX4-Autopilot (where this file is deployed from). Thanks
