### ISSUE TITLE
'make px4_sitl_rtps gazebo' using custom world and model 

### ISSUE THREAD

**Issue by yyq5987** [PX4/px4_ros_com#97]
Hi, I'm new here and I'm following the PX4 User Guide for ROS2 (https://docs.px4.io/master/en/ros/ros2_comm.html). 

After building all the things required, this command **make px4_sitl_rtps gazebo** did work successfully. I can see in the terminal that this simulation uses the default world 'empty.world' and 'iris.sdf' as model. 

And my problem is that, how can I edit some related files in order to start my simulation with the custom world and custom model using this command? 

Thank you in advance!

**Comment by TSC21** [comment]
This is documented in https://docs.px4.io/master/en/simulation/gazebo.html, though unrelated with this repo. Closing.
